#!/bin/sh
# postinst script for retromod core
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)
        release=$(lsb_release -sc)


        chmod a+x /usr/lib/flywire/run.sh
        exit 0
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
